noVillagerWitchConversion true
vexesNerf true
commandLog true
mobsDropNametag true
xpNoCooldown false
ctrlQCraftingFix true
commandTrackAI true
commandScriptACE 0
commandPlayer true
antiCheatDisabled true
missingTools true
removableCurses true
cleanLogs true
noFeatherFallingTrample true
stackableShulkerBoxes false
shulkerSpawningInEndCities true
renewableCoral true
villagersAlwaysConvert true
deathItemsDespawnMinutes -1
scriptsDebugging true
creativeNoClip true
smoothClientAnimations true
commandTick 0
placementRotationFix true
quickHarvesting true
renewableDragonEgg true
