#This file stores configuration options for Iris, such as the currently active shaderpack
#Sat Apr 11 21:02:28 GMT+05:45 2026
allowUnknownShaders=false
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
enableShaders=false
maxShadowRenderDistance=0
shaderPack=MakeUp-UltraFast-9.3e.zip
